baseurl = "/"
languageCode = "en-us"
title = "H채usle in Cornwall"
theme = "internet-weblog"
pygmentsstyle = "emacs"
Paginate = 10
SectionPagesMenu = "main"
assetDir = "static/"

# Google Analytics UA number
googleAnalytics = "UA-XXXXXXXX-X"

[author]
   Handle = "H채usle"
   FirstName = "H채usle"
   LastName = "in Cornwall"
   AboutPage = "/about"
   Location = "Redruth, UK"
   FlickrID = "145760991@N03"

[params]
   Description = "H채usle in Cornwall. Urlaub machen wie bei Rosamund Pilcher"
   ShowCopyright = true
   RSSEnabled = true
   RSSSections = [ "Posts", "Microposts", "Photos" ]
   twitter = "@husle15"
   opengraphimage = "/images/uploads/ripple.jpg" #default if no thumbnail is used in the post.
   logo = "/images/uploads/hausle_in_cornwall.png"

[taxonomies]
   tag = "tags"
   category = "categories"
   series = "series"

[[menu.main]]
   name = "Posts"
   weight = 1
   identifier = "posts"
   url = "/posts/"

[[menu.main]]
   name = "Microposts"
   weight = 2
   identifier = "microposts"
   url = "/microposts/"

[[menu.main]]
   name = "Photos"
   weight = 3
   identifier = "photos"
   url = "/photos/"
